### PR TITLE
Add secondary mirror to README.md

### PR DESCRIPTION
**Pull request by SwiftWinds**
I've noticed that the game hosted at sloppy.zone has been going down recently. I'm offering to host it on my servers for free to anyone who wants to play it. I'll do my best to keep it up for the foreseeable future.

I hope linking it on the README.md will increase visibility so more players can access the game if the sloppy.zone server is ever down. :)

Additionally, games on my server are cached for 24 hours instead of 2, so as long as your last move was within the last day, the game will not be cleared.

### CODE REVIEW

**Comment by caphindsight** [comment]
Thanks, I'm glad people like this game still :)

**Comment by caphindsight** [comment]
Btw, your link doesn't seem to work for me either :D
The landing page opens just fine, but I can't start the new game.
Perhaps the web server can't connect to the database?

**Comment by SwiftWinds** [comment]
> The landing page opens just fine, but I can't start the new game.

Weird. It works for me... there is a bit of lag, but I've been playing games with my friend in India (I'm from the US), and it works fine. Maybe you just need to wait a few moments?

**Comment by caphindsight** [comment]
I tried it again and it works. I think there must have been some sort of a database outage over the weekend.

**Comment by SwiftWinds** [comment]
Ah yeah, perhaps. Good to hear it works for you now :)

**Pull request merged**
